# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.cache/wt [current_project]
set_property parent.project_path C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/Y_shift_register.v
  {C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/CMPE 125 Lab 7 Small Calculator DP Source Code/alu.v}
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/new/and2.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/bcd_to_7seg.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/button_debouncer.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/new/cla.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/new/cla8.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/clk_gen.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/comparator.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/divider.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/divider_control_unit.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/divider_data_path.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/new/en_flop.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/new/flop.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/new/full_calc_cu.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/new/full_calc_cu_dp.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/new/full_calc_dp.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/new/half_adder.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/led_mux.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/new/multiplier.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/mux2.v
  {C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/CMPE 125 Lab 7 Small Calculator DP Source Code/mux4.v}
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/new/pp.v
  {C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/CMPE 125 Lab 7 Small Calculator DP Source Code/register_file.v}
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/shift_register.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/new/small_calc_cu.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/new/small_calc_cu_dp.v
  {C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/CMPE 125 Lab 7 Small Calculator DP Source Code/small_calculator_dp.v}
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/subtractor.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/new/ud_counter.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/imports/sources_1/imports/new/xor2.v
  C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/sources_1/new/full_calc_fpga.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files C:/Users/Ali/Documents/cmpe_125_lab_9/extra_credit/extra_credit.srcs/constrs_1/new/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top full_calc_fpga -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef full_calc_fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file full_calc_fpga_utilization_synth.rpt -pb full_calc_fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
